import type { NormalizedListing } from "./types";

function dagen(offset: number): Date {
  return new Date(Date.now() + offset * 86_400_000);
}
function uren(offset: number): Date {
  return new Date(Date.now() + offset * 3_600_000);
}

/**
 * Realistische testdata voor de demo-DAK-connector (regio Drechtsteden / Dordrecht).
 */
export const DAK_TESTDATA: NormalizedListing[] = [
  {
    externalId: "dak-1001",
    bronUrl: "https://demo.mijndak.nl/woning/1001",
    plaats: "Dordrecht",
    wijk: "Krispijn",
    gemeente: "Dordrecht",
    regio: "drechtsteden",
    corporatie: "Woonbron",
    huurprijs: 682,
    servicekosten: 34,
    oppervlakte: 68,
    kamers: 3,
    slaapkamers: 2,
    woningtype: "APPARTEMENT",
    verdeelmodel: "LOTING",
    verdiepingen: 2,
    heeftLift: true,
    beganeGrond: false,
    maxInkomen: 47000,
    gepubliceerdOp: uren(-3),
    sluitDatum: uren(19),
    titel: "Ruim 3-kamerappartement in Krispijn",
    omschrijving:
      "Lichte woning met balkon. Toewijzing via loting onder passende kandidaten.",
  },
  {
    externalId: "dak-1002",
    bronUrl: "https://demo.mijndak.nl/woning/1002",
    plaats: "Zwijndrecht",
    wijk: "Centrum",
    gemeente: "Zwijndrecht",
    regio: "drechtsteden",
    corporatie: "Woonkracht10",
    huurprijs: 597,
    servicekosten: 22,
    oppervlakte: 52,
    kamers: 2,
    slaapkamers: 1,
    woningtype: "BENEDENWONING",
    verdeelmodel: "INSCHRIJFDUUR",
    beganeGrond: true,
    heeftLift: false,
    maxInkomen: 44000,
    gepubliceerdOp: dagen(-1),
    sluitDatum: dagen(5),
    titel: "Benedenwoning met tuin",
    omschrijving: "Toewijzing op inschrijfduur. Gelijkvloers met eigen tuin.",
  },
  {
    externalId: "dak-1003",
    bronUrl: "https://demo.mijndak.nl/woning/1003",
    plaats: "Dordrecht",
    wijk: "Sterrenburg",
    gemeente: "Dordrecht",
    regio: "drechtsteden",
    corporatie: "Trivire",
    huurprijs: 745,
    servicekosten: 41,
    oppervlakte: 78,
    kamers: 4,
    slaapkamers: 3,
    woningtype: "EENGEZINSWONING",
    verdeelmodel: "DIRECT_KANS",
    beganeGrond: false,
    heeftLift: false,
    maxInkomen: 52000,
    minHuishoudgrootte: 2,
    gepubliceerdOp: uren(-1),
    sluitDatum: uren(30),
    titel: "Eengezinswoning voor gezin",
    omschrijving:
      "Direct te huur: wie het eerst passend reageert, maakt de meeste kans.",
  },
  {
    externalId: "dak-1004",
    bronUrl: "https://demo.mijndak.nl/woning/1004",
    plaats: "Papendrecht",
    wijk: "Wilgendonk",
    gemeente: "Papendrecht",
    regio: "drechtsteden",
    corporatie: "Woonkracht10",
    huurprijs: 612,
    servicekosten: 58,
    oppervlakte: 61,
    kamers: 2,
    woningtype: "SENIORENWONING",
    verdeelmodel: "SENIORENWONING",
    minLeeftijd: 55,
    heeftLift: true,
    beganeGrond: false,
    maxInkomen: 44000,
    gepubliceerdOp: dagen(-2),
    sluitDatum: dagen(3),
    titel: "Seniorenappartement 55+ met lift",
    doelgroep: "senioren 55+",
    omschrijving: "Gelijkvloers appartement met lift, doelgroep 55 jaar en ouder.",
  },
];

/**
 * Testdata voor demo-Woonnet-Rijnmond-connector (regio Rotterdam-Rijnmond).
 */
export const RIJNMOND_TESTDATA: NormalizedListing[] = [
  {
    externalId: "rijnmond-2001",
    bronUrl: "https://demo.woonnetrijnmond.nl/aanbod/2001",
    plaats: "Rotterdam",
    wijk: "Delfshaven",
    gemeente: "Rotterdam",
    regio: "rotterdam",
    corporatie: "Woonstad Rotterdam",
    huurprijs: 689,
    servicekosten: 45,
    oppervlakte: 64,
    kamers: 3,
    slaapkamers: 2,
    woningtype: "APPARTEMENT",
    verdeelmodel: "LOTING",
    verdiepingen: 3,
    heeftLift: true,
    maxInkomen: 47000,
    gepubliceerdOp: uren(-5),
    sluitDatum: uren(19),
    titel: "3-kamerappartement Delfshaven",
    omschrijving: "Toewijzing via loting. Nabij metro en winkels.",
  },
  {
    externalId: "rijnmond-2002",
    bronUrl: "https://demo.woonnetrijnmond.nl/aanbod/2002",
    plaats: "Schiedam",
    wijk: "Nieuwland",
    gemeente: "Schiedam",
    regio: "rotterdam",
    corporatie: "Woonplus Schiedam",
    huurprijs: 574,
    servicekosten: 30,
    oppervlakte: 48,
    kamers: 2,
    woningtype: "APPARTEMENT",
    verdeelmodel: "INSCHRIJFDUUR",
    heeftLift: false,
    verdiepingen: 2,
    maxInkomen: 44000,
    gepubliceerdOp: dagen(-1),
    sluitDatum: dagen(6),
    titel: "2-kamerwoning Nieuwland",
    omschrijving: "Toewijzing op inschrijfduur.",
  },
  {
    externalId: "rijnmond-2003",
    bronUrl: "https://demo.woonnetrijnmond.nl/aanbod/2003",
    plaats: "Rotterdam",
    wijk: "Kralingen",
    gemeente: "Rotterdam",
    regio: "rotterdam",
    corporatie: "Havensteder",
    huurprijs: 619,
    servicekosten: 38,
    oppervlakte: 42,
    kamers: 2,
    woningtype: "STUDIO",
    verdeelmodel: "JONGERENWONING",
    maxLeeftijd: 27,
    heeftLift: true,
    maxInkomen: 40000,
    gepubliceerdOp: uren(-8),
    sluitDatum: dagen(2),
    titel: "Jongerenstudio Kralingen (t/m 27 jaar)",
    doelgroep: "jongeren t/m 27",
    omschrijving: "Jongerenwoning voor kandidaten tot en met 27 jaar.",
  },
  {
    externalId: "rijnmond-2004",
    bronUrl: "https://demo.woonnetrijnmond.nl/aanbod/2004",
    plaats: "Rotterdam",
    wijk: "IJsselmonde",
    gemeente: "Rotterdam",
    regio: "rotterdam",
    corporatie: "Vestia",
    huurprijs: 763,
    servicekosten: 52,
    oppervlakte: 82,
    kamers: 4,
    slaapkamers: 3,
    woningtype: "EENGEZINSWONING",
    verdeelmodel: "LOKALE_VOORRANG",
    lokaleBindingGemeente: "Rotterdam",
    heeftLift: false,
    beganeGrond: false,
    maxInkomen: 52000,
    minHuishoudgrootte: 3,
    gepubliceerdOp: dagen(-3),
    sluitDatum: dagen(1),
    titel: "Eengezinswoning IJsselmonde",
    omschrijving: "Lokale voorrang voor inwoners van Rotterdam.",
  },
];

/** Voorbeeld JSON-feed payload (zoals een extern platform zou aanleveren). */
export const JSON_FEED_TESTDATA = {
  platform: "woonmatch-demo",
  woningen: [
    {
      id: "wm-3001",
      url: "https://demo.woonmatch.nl/woning/3001",
      stad: "Alkmaar",
      buurt: "Overdie",
      gemeente: "Alkmaar",
      regio: "noord-holland-noord",
      corporatie: "Woonwaard",
      prijs: 634,
      servicekosten: 29,
      m2: 58,
      kamers: 3,
      type: "APPARTEMENT",
      model: "loting",
      lift: true,
      maxInkomen: 47000,
      gepubliceerd: uren(-6).toISOString(),
      sluit: dagen(4).toISOString(),
      titel: "3-kamerappartement Overdie",
    },
  ],
};
